version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run: yarn install
      - run: COVERALLS_REPO_TOKEN=lF0bZaq3k7pfj5OFFwsiJ5z3AIPm8dduO yarn test